--NUEVA TABLA POSICION
--DROP TABLE MIFIDIICYG.POSICION;
CREATE TABLE MIFIDIICYG.POSICION (
	POS_IDEMPR VARCHAR(4) NOT NULL,	 
	POS_IDCENT	VARCHAR(4) NOT NULL,	 
	POS_IDPRO VARCHAR(3) NOT NULL,	 
	POS_IDCONTR	VARCHAR(7) NOT NULL,	 
	POS_ISIN VARCHAR(12) NOT NULL,	 
	--POS_CODVAL VARCHAR(4) NOT NULL,	 	 	 	 	 
	POS_IDINSFIN VARCHAR(2),
	POS_CALC1 DECIMAL(17, 2), 	 	 
	POS_CALC2 DECIMAL(17, 2), 	 	 
	POS_CALC3 DECIMAL(17, 2), 	 	 
	POS_CALC4 DECIMAL(17, 2), 	 	 
	POS_CALC5 DECIMAL(17, 2), 	 	 
	POS_CALC6 DECIMAL(17, 2), 	 	 
	POS_CALC7 DECIMAL(17, 2), 	 	 
	POS_CALC8 DECIMAL(17, 2), 	 	 
	POS_CALC9 DECIMAL(17, 2), 	 	 
	POS_CALC10 DECIMAL(17, 2));
                               
ALTER TABLE MIFIDIICYG.POSICION ADD CONSTRAINT PK_POSICION PRIMARY KEY (POS_IDEMPR, POS_IDCENT, POS_IDPRO, POS_IDCONTR, POS_ISIN);

COMMENT ON TABLE MIFIDIICYG.POSICION IS 'Posicion';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_IDEMPR IS 'Contrato empresa';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_IDCENT IS 'Contrato centro';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_IDPRO IS 'Contrato tipo producto';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_IDCONTR IS 'Contrato numero';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_ISIN IS 'ISIN';
--COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CODVAL IS 'Codigo de valor';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_IDINSFIN IS 'Numero Instrumento financiero';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC1 IS 'Variable de calculo 1';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC2 IS 'Variable de calculo 2';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC3 IS 'Variable de calculo 3';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC4 IS 'Variable de calculo 4';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC5 IS 'Variable de calculo 5';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC6 IS 'Variable de calculo 6';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC7 IS 'Variable de calculo 7';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC8 IS 'Variable de calculo 8';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC9 IS 'Variable de calculo 9';
COMMENT ON COLUMN MIFIDIICYG.POSICION.POS_CALC10 IS 'Variable de calculo 10';


--NUEVA TABLA OPER_LIQUIDADA
--DROP TABLE MIFIDIICYG.OPER_LIQUIDADA;
CREATE TABLE MIFIDIICYG.OPER_LIQUIDADA (
	OPL_IDEMPR VARCHAR(4) NOT NULL,	 
	OPL_IDCENT	VARCHAR(4) NOT NULL,	 
	OPL_IDPRO VARCHAR(3) NOT NULL,	 
	OPL_IDCONTR	VARCHAR(7) NOT NULL,	 
	OPL_ISIN VARCHAR(12) NOT NULL,	 
	OPL_INDOPE CHAR(1) NOT NULL,
	OPL_NUMOPE VARCHAR(21) NOT NULL,
	--OPL_CODVAL VARCHAR(4) NOT NULL,	 
	OPL_IDINSFIN VARCHAR(2),
	OPL_FECORD DATE,
	OPL_FECCONT DATE,
	OPL_TIPOPE VARCHAR(4),
	OPL_CENTEJEC VARCHAR(4),	 	 	 
    OPL_CONTRAP VARCHAR(4),
    OPL_TIPCAMB DECIMAL(17, 12),
    OPL_ISINFOND VARCHAR(12),
	OPL_IMNOMDIV DECIMAL(17, 2),
    OPL_IMNOMCON DECIMAL(17, 2),	 	 
	OPL_DIVISA VARCHAR(3),  	 	 
    OPL_DIVDES VARCHAR(3),	 	 	 
    OPL_EOPERDIV DECIMAL(17, 2), 
    OPL_EOPERCON DECIMAL(17, 2),
    OPL_TITOPE DECIMAL(17, 5)
);

ALTER TABLE MIFIDIICYG.OPER_LIQUIDADA ADD CONSTRAINT PK_OPER_LIQUIDADA PRIMARY KEY (OPL_IDEMPR, OPL_IDCENT, OPL_IDPRO, OPL_IDCONTR, OPL_ISIN, OPL_INDOPE, OPL_NUMOPE);

COMMENT ON TABLE MIFIDIICYG.OPER_LIQUIDADA IS 'Posicion liquidada';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IDEMPR IS 'Contrato empresa';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IDCENT IS 'Contrato centro';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IDPRO IS 'Contrato tipo producto';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IDCONTR IS 'Contrato numero';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_ISIN IS 'ISIN';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_INDOPE IS 'Indicador operacion real';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_NUMOPE IS 'Operacion';
--COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_CODVAL IS 'Codigo de valor';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IDINSFIN IS 'Numero instrumento financiero';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_FECORD IS 'Fecha Orden';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_FECCONT IS 'Fecha Contratacion';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_TIPOPE IS 'Tipo de Operacion';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_CENTEJEC IS 'Centro ejecucion';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_CONTRAP IS 'Contrapartida';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_TIPCAMB IS 'Tipo de Cambio';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_ISINFOND IS 'ISIN Fondo destino ';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IMNOMDIV IS 'Importe Nominal-Divisa';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_IMNOMCON IS 'Importe Nominal-Contravalor';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_DIVISA IS 'Divisa';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_DIVDES IS 'Divisa destino (Seguros de Cambio)';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_EOPERDIV IS 'Efectivo Operacion-Divisa';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_EOPERCON IS 'Efectivo Operacion-Contravalor';
COMMENT ON COLUMN MIFIDIICYG.OPER_LIQUIDADA.OPL_TITOPE IS 'Titulos operacion';


--NUEVA TABLA IMPORTE_COBRADO
--DROP TABLE MIFIDIICYG.IMP_COBRADO;
CREATE TABLE MIFIDIICYG.IMP_COBRADO(
	ICOB_IDEMPR VARCHAR(4) NOT NULL,	 
	ICOB_IDCENT	VARCHAR(4) NOT NULL,	 
	ICOB_IDPRO VARCHAR(3) NOT NULL,	 
	ICOB_IDCONTR VARCHAR(7) NOT NULL,	 
	ICOB_ISIN VARCHAR(12) NOT NULL,	 
	ICOB_INDOPE CHAR(1) NOT NULL,
	ICOB_NUMOPE VARCHAR(21) NOT NULL,
	ICOB_IDCYGI VARCHAR(3) NOT NULL,
	ICOB_IMPCYG DECIMAL(17,2)
);

ALTER TABLE MIFIDIICYG.IMP_COBRADO ADD CONSTRAINT PK_IMP_COBRADO PRIMARY KEY (ICOB_IDEMPR, ICOB_IDCENT, ICOB_IDPRO, ICOB_IDCONTR, 
                                                                                  ICOB_ISIN, ICOB_INDOPE, ICOB_NUMOPE, ICOB_IDCYGI);

COMMENT ON TABLE MIFIDIICYG.IMP_COBRADO IS 'Importe cobrado';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IDEMPR IS 'Contrato empresa';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IDCENT IS 'Contrato centro';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IDPRO IS 'Contrato tipo producto';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IDCONTR IS 'Contrato numero';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_ISIN IS 'ISIN';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_INDOPE IS 'Indicador operacion real';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_NUMOPE IS 'Operacion';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IDCYGI IS 'Numero de CyG o Incentivo';
COMMENT ON COLUMN MIFIDIICYG.IMP_COBRADO.ICOB_IMPCYG IS 'Importe CyG';


--NUEVA TABLA IMPORTE_CYG
DROP TABLE MIFIDIICYG.IMP_CYG;
CREATE TABLE MIFIDIICYG.IMP_CYG (
	ICYG_IDCYGI VARCHAR(3) NOT NULL,
	ICYG_DESCRIP VARCHAR(50),
    ICYG_DETALLE VARCHAR(500),
    ICYG_CYGI VARCHAR(1),
    ICYG_CATEG VARCHAR(1),
    ICYG_BANCTERC VARCHAR(1)
 );

ALTER TABLE MIFIDIICYG.IMP_CYG ADD CONSTRAINT PK_IMP_CYG PRIMARY KEY (ICYG_IDCYGI);
 
COMMENT ON TABLE MIFIDIICYG.IMP_CYG IS 'Importe Costes y Gastos';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_IDCYGI IS 'Numero de CyG o Incentivo';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_DESCRIP IS 'Descripcion';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_DETALLE IS 'Detalle explicativo';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_CYGI IS 'CyG / Inc';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_CATEG IS 'Categoria';
COMMENT ON COLUMN MIFIDIICYG.IMP_CYG.ICYG_BANCTERC IS 'Banco / Terceros';


--NUEVA TABLA INS_FINANCIERO
--DROP TABLE MIFIDIICYG.INS_FINANCIERO; 
CREATE TABLE MIFIDIICYG.INS_FINANCIERO(
	IFIN_IDINSFIN VARCHAR(2) NOT NULL,
	--IFIN_CODINSFIN
	IFIN_DESCRIP VARCHAR(20),
	IFIN_AGRUPACION VARCHAR(2)
);

ALTER TABLE MIFIDIICYG.INS_FINANCIERO ADD CONSTRAINT PK_INS_FINANCIERO PRIMARY KEY (IFIN_IDINSFIN);

COMMENT ON TABLE MIFIDIICYG.INS_FINANCIERO IS 'Instrumento financiero';
COMMENT ON COLUMN MIFIDIICYG.INS_FINANCIERO.IFIN_IDINSFIN IS 'Numero Instrumento Financiero';
--COMMENT ON COLUMN MIFIDIICYG.INS_FINANCIERO.IFIN_CODINSFIN IS 'Codigo instrumento financiero';
COMMENT ON COLUMN MIFIDIICYG.INS_FINANCIERO.IFIN_DESCRIP IS 'Descripcion Producto ';
COMMENT ON COLUMN MIFIDIICYG.INS_FINANCIERO.IFIN_AGRUPACION IS 'Agrupacion';



--NUEVA TABLA INS_IMPORTE
--DROP TABLE MIFIDIICYG.INS_IMPORTE;
CREATE TABLE MIFIDIICYG.INS_IMPORTE(
	IIMP_IDINSFIN VARCHAR(2) NOT NULL,
	IIMP_CYGI VARCHAR(3) NOT NULL
);

ALTER TABLE MIFIDIICYG.INS_IMPORTE ADD CONSTRAINT PK_INS_IMPORTE PRIMARY KEY (IIMP_IDINSFIN, IIMP_CYGI);

COMMENT ON TABLE MIFIDIICYG.INS_IMPORTE IS 'Instrumento importe';
COMMENT ON COLUMN MIFIDIICYG.INS_IMPORTE.IIMP_IDINSFIN IS 'Numero Instrumento Financiero';
COMMENT ON COLUMN MIFIDIICYG.INS_IMPORTE.IIMP_CYGI IS 'Numero de CyG o Incentivo';